/**
 * Project templates for common Portuguese building types.
 * Pre-fills BuildingProject fields so users start from a realistic baseline
 * instead of filling 200+ fields from scratch.
 */

import type { BuildingProject } from "./types";
import { DEFAULT_PROJECT } from "./defaults";

export interface ProjectTemplate {
  id: string;
  nameKey: string; // i18n key
  descriptionKey: string; // i18n key
  icon: string; // emoji
  category: "residential" | "commercial" | "mixed";
  project: BuildingProject;
}

function template(
  id: string,
  nameKey: string,
  descriptionKey: string,
  icon: string,
  category: ProjectTemplate["category"],
  overrides: Partial<BuildingProject> & { [K in keyof BuildingProject]?: Partial<BuildingProject[K]> extends object ? Partial<BuildingProject[K]> : BuildingProject[K] },
): ProjectTemplate {
  // Deep merge overrides into DEFAULT_PROJECT
  const project: BuildingProject = {
    ...DEFAULT_PROJECT,
    ...overrides,
    location: { ...DEFAULT_PROJECT.location, ...(overrides.location ?? {}) },
    architecture: { ...DEFAULT_PROJECT.architecture, ...(overrides.architecture ?? {}) },
    structural: { ...DEFAULT_PROJECT.structural, ...(overrides.structural ?? {}) },
    fireSafety: { ...DEFAULT_PROJECT.fireSafety, ...(overrides.fireSafety ?? {}) },
    avac: { ...DEFAULT_PROJECT.avac, ...(overrides.avac ?? {}) },
    waterDrainage: { ...DEFAULT_PROJECT.waterDrainage, ...(overrides.waterDrainage ?? {}) },
    gas: { ...DEFAULT_PROJECT.gas, ...(overrides.gas ?? {}) },
    electrical: { ...DEFAULT_PROJECT.electrical, ...(overrides.electrical ?? {}) },
    telecommunications: { ...DEFAULT_PROJECT.telecommunications, ...(overrides.telecommunications ?? {}) },
    envelope: { ...DEFAULT_PROJECT.envelope, ...(overrides.envelope ?? {}) },
    systems: { ...DEFAULT_PROJECT.systems, ...(overrides.systems ?? {}) },
    acoustic: { ...DEFAULT_PROJECT.acoustic, ...(overrides.acoustic ?? {}) },
    accessibility: { ...DEFAULT_PROJECT.accessibility, ...(overrides.accessibility ?? {}) },
    elevators: { ...DEFAULT_PROJECT.elevators, ...(overrides.elevators ?? {}) },
    licensing: { ...DEFAULT_PROJECT.licensing, ...(overrides.licensing ?? {}) },
    waste: { ...DEFAULT_PROJECT.waste, ...(overrides.waste ?? {}) },
    localRegulations: { ...DEFAULT_PROJECT.localRegulations, ...(overrides.localRegulations ?? {}) },
    drawingQuality: { ...DEFAULT_PROJECT.drawingQuality, ...(overrides.drawingQuality ?? {}) },
    projectContext: { ...DEFAULT_PROJECT.projectContext, ...(overrides.projectContext ?? {}) },
  } as BuildingProject;
  return { id, nameKey, descriptionKey, icon, category, project };
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  // ── Moradia T3 ──────────────────────────────────────
  template(
    "moradia_t3",
    "templateMoradiaT3",
    "templateMoradiaT3Desc",
    "🏠",
    "residential",
    {
      name: "Moradia T3",
      buildingType: "residential",
      grossFloorArea: 200,
      usableFloorArea: 170,
      numberOfFloors: 2,
      buildingHeight: 7,
      numberOfDwellings: 1,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: false,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 2.7,
        hasNaturalLight: true,
        hasCrossVentilation: true,
      },
      structural: {
        structuralSystem: "reinforced_concrete",
        seismicZone: "1.3",
        soilType: "B",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "shallow",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "I",
        riskCategory: "1",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.0,
        numberOfExits: 2,
        maxEvacuationDistance: 15,
        fireResistanceOfStructure: 30,
      },
      avac: {
        hasHVACProject: false,
        hasVentilationSystem: false,
        ventilationType: "natural",
        hasKitchenExtraction: true,
        hasBathroomExtraction: true,
        hasDuctwork: false,
        hasAirQualityControl: false,
        hasMaintenancePlan: false,
        hasFGasCompliance: false,
        hasRadonProtection: false,
      },
      waterDrainage: {
        hasPublicWaterConnection: true,
        waterPipeMaterial: "multicamada",
        hasWaterMeter: true,
        hasCheckValve: true,
        hasPressureReducer: true,
        hotWaterRecirculation: false,
        hasSeparateDrainageSystem: true,
        hasVentilatedDrainage: true,
        hasDrainageSiphons: true,
        hasGreaseTrap: false,
        hasStormwaterManagement: true,
        hasWaterReuse: false,
        hasBackflowPrevention: true,
      },
      gas: {
        hasGasInstallation: true,
        gasType: "natural_gas",
        hasGasProject: true,
        hasGasDetector: true,
        hasEmergencyValve: true,
        hasVentilation: true,
        hasFlueSystem: true,
        pipesMaterial: "copper",
        hasPressureTest: true,
        hasGasCertification: true,
      },
      electrical: {
        supplyType: "single_phase",
        contractedPower: 10.35,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 10,
        hasEquipotentialBonding: true,
        wiringType: "embedded",
        cableType: "h07v",
        hasCorrectCableSizing: true,
        numberOfCircuits: 8,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: false,
        hasEmergencyCircuit: false,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      telecommunications: {
        itedEdition: "4",
        hasATE: false,
        hasATI: true,
        numberOfATI: 1,
        hasCopperCabling: true,
        copperCableCategory: "6",
        hasFiberOptic: true,
        fiberType: "single_mode",
        hasCoaxialCabling: true,
        hasFoorDistribution: false,
        hasRiserCableway: false,
        hasIndividualDucts: true,
        rj45OutletsPerDwelling: 6,
        coaxialOutletsPerDwelling: 3,
        fiberOutletsPerDwelling: 1,
        isUrbanization: false,
        hasITURProject: false,
        hasUndergroundDucts: false,
        hasCEE: false,
        hasITEDCertification: true,
        installerITEDLicense: true,
      },
      envelope: {
        externalWallUValue: 0.35,
        externalWallArea: 250,
        roofUValue: 0.30,
        roofArea: 100,
        floorUValue: 0.40,
        floorArea: 100,
        windowUValue: 2.40,
        windowArea: 30,
        windowSolarFactor: 0.40,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.30,
        airChangesPerHour: 0.6,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "heat_pump",
        dhwSystem: "heat_pump",
        hasSolarPV: true,
        solarPVCapacity: 3.5,
        hasSolarThermal: true,
        solarThermalArea: 4,
      },
      acoustic: {
        buildingLocation: "quiet",
        hasAirborneInsulation: false,
        hasImpactInsulation: false,
        hasFacadeInsulation: true,
        hasEquipmentNoiseControl: false,
        hasAcousticProject: false,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: false,
        doorWidths: 0.90,
        corridorWidths: 1.20,
        hasAccessibleWC: false,
        hasAccessibleParking: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
      waste: {
        hasWasteManagementPlan: true,
        hasSortingOnSite: true,
        hasLicensedTransporter: true,
        hasLicensedDestination: true,
        hasWasteRegistration: true,
        hasDemolitionAudit: false,
        recyclingPercentageTarget: 70,
      },
      drawingQuality: {
        architectureScale: "1:100",
        detailScale: "1:20",
        locationPlanScale: "1:1000",
        hasCorrectScaleForPrint: true,
        hasConsistentFonts: true,
        hasReadableTextAtScale: true,
        hasStandardSymbols: true,
        hasLegendOnEverySheet: true,
        hasNorthArrow: true,
        hasScaleBar: true,
        hasConsistentLineWeights: true,
        hasDimensioning: true,
        hasSheetTitleBlock: true,
      },
    },
  ),

  // ── Apartamento T2 ──────────────────────────────────
  template(
    "apartamento_t2",
    "templateApartamentoT2",
    "templateApartamentoT2Desc",
    "🏢",
    "residential",
    {
      name: "Apartamento T2",
      buildingType: "residential",
      grossFloorArea: 90,
      usableFloorArea: 75,
      numberOfFloors: 5,
      buildingHeight: 15,
      numberOfDwellings: 10,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: true,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 2.70,
        hasNaturalLight: true,
        hasCrossVentilation: false,
      },
      structural: {
        structuralSystem: "reinforced_concrete",
        seismicZone: "1.3",
        soilType: "B",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "deep",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "I",
        riskCategory: "2",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.4,
        numberOfExits: 2,
        maxEvacuationDistance: 25,
        fireResistanceOfStructure: 60,
      },
      avac: {
        hasHVACProject: true,
        hasVentilationSystem: true,
        ventilationType: "mechanical_extract",
        hasKitchenExtraction: true,
        hasBathroomExtraction: true,
        hasDuctwork: true,
        hasAirQualityControl: false,
        hasMaintenancePlan: true,
        hasFGasCompliance: false,
        hasRadonProtection: false,
      },
      waterDrainage: {
        hasPublicWaterConnection: true,
        waterPipeMaterial: "multicamada",
        hasWaterMeter: true,
        hasCheckValve: true,
        hasPressureReducer: true,
        hotWaterRecirculation: true,
        hasSeparateDrainageSystem: true,
        hasVentilatedDrainage: true,
        hasDrainageSiphons: true,
        hasGreaseTrap: false,
        hasStormwaterManagement: true,
        hasWaterReuse: false,
        hasBackflowPrevention: true,
      },
      electrical: {
        supplyType: "single_phase",
        contractedPower: 6.9,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 10,
        hasEquipotentialBonding: true,
        wiringType: "embedded",
        cableType: "h07v",
        hasCorrectCableSizing: true,
        numberOfCircuits: 6,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: false,
        hasEVCharging: false,
        hasEmergencyCircuit: false,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      telecommunications: {
        itedEdition: "4",
        hasATE: true,
        hasATI: true,
        numberOfATI: 1,
        hasCopperCabling: true,
        copperCableCategory: "6",
        hasFiberOptic: true,
        fiberType: "single_mode",
        hasCoaxialCabling: true,
        hasFoorDistribution: true,
        hasRiserCableway: true,
        hasIndividualDucts: true,
        rj45OutletsPerDwelling: 4,
        coaxialOutletsPerDwelling: 2,
        fiberOutletsPerDwelling: 1,
        isUrbanization: false,
        hasITURProject: false,
        hasUndergroundDucts: false,
        hasCEE: false,
        hasITEDCertification: true,
        installerITEDLicense: true,
      },
      envelope: {
        externalWallUValue: 0.40,
        externalWallArea: 60,
        roofUValue: 0.35,
        roofArea: 0,
        floorUValue: 0.45,
        floorArea: 0,
        windowUValue: 2.80,
        windowArea: 12,
        windowSolarFactor: 0.42,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.40,
        airChangesPerHour: 0.6,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "split_ac",
        dhwSystem: "heat_pump",
        hasSolarPV: true,
        solarPVCapacity: 1.5,
        hasSolarThermal: true,
        solarThermalArea: 2,
      },
      acoustic: {
        buildingLocation: "mixed",
        hasAirborneInsulation: true,
        hasImpactInsulation: true,
        hasFacadeInsulation: true,
        hasEquipmentNoiseControl: true,
        hasAcousticProject: true,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: true,
        doorWidths: 0.90,
        corridorWidths: 1.40,
        hasAccessibleWC: true,
        hasAccessibleParking: true,
      },
      elevators: {
        hasElevator: true,
        numberOfElevators: 1,
        elevatorType: "passenger",
        hasCEMarking: true,
        hasMaintenanceContract: true,
        hasPeriodicInspection: true,
        hasEmergencyCommunication: true,
        hasPitAndHeadroom: true,
        hasAccessibleElevator: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
    },
  ),

  // ── Loja Comercial ──────────────────────────────────
  template(
    "loja_comercial",
    "templateLojaComercial",
    "templateLojaComercialDesc",
    "🏪",
    "commercial",
    {
      name: "Loja Comercial",
      buildingType: "commercial",
      grossFloorArea: 150,
      usableFloorArea: 130,
      numberOfFloors: 1,
      buildingHeight: 4,
      numberOfDwellings: 0,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: true,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 3.0,
        hasNaturalLight: true,
        hasCrossVentilation: false,
      },
      fireSafety: {
        utilizationType: "VIII",
        riskCategory: "1",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.4,
        numberOfExits: 2,
        maxEvacuationDistance: 30,
        fireResistanceOfStructure: 60,
      },
      avac: {
        hasHVACProject: true,
        hasVentilationSystem: true,
        ventilationType: "mechanical_supply_extract",
        hasKitchenExtraction: false,
        hasBathroomExtraction: true,
        hasDuctwork: true,
        hasAirQualityControl: true,
        hasMaintenancePlan: true,
        hasFGasCompliance: true,
        hasRadonProtection: false,
      },
      electrical: {
        supplyType: "three_phase",
        contractedPower: 20.7,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 5,
        hasEquipotentialBonding: true,
        wiringType: "cable_tray",
        cableType: "xv",
        hasCorrectCableSizing: true,
        numberOfCircuits: 12,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: false,
        hasEmergencyCircuit: true,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      envelope: {
        externalWallUValue: 0.45,
        externalWallArea: 80,
        roofUValue: 0.40,
        roofArea: 150,
        floorUValue: 0.50,
        floorArea: 150,
        windowUValue: 3.00,
        windowArea: 25,
        windowSolarFactor: 0.35,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.40,
        airChangesPerHour: 0.8,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "central_ac",
        dhwSystem: "electric",
        hasSolarPV: false,
        hasSolarThermal: false,
        lightingPowerDensity: 10,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: false,
        doorWidths: 1.00,
        corridorWidths: 1.50,
        hasAccessibleWC: true,
        hasAccessibleParking: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
    },
  ),

  // ── Edifício Multifamiliar ──────────────────────────
  template(
    "edificio_multifamiliar",
    "templateMultifamiliar",
    "templateMultifamiliarDesc",
    "🏗️",
    "residential",
    {
      name: "Edifício Multifamiliar",
      buildingType: "residential",
      grossFloorArea: 2000,
      usableFloorArea: 1600,
      numberOfFloors: 8,
      buildingHeight: 25,
      numberOfDwellings: 24,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: true,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 2.70,
        hasNaturalLight: true,
        hasCrossVentilation: false,
      },
      structural: {
        structuralSystem: "reinforced_concrete",
        seismicZone: "1.3",
        soilType: "C",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "deep",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "I",
        riskCategory: "3",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: true,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.8,
        numberOfExits: 2,
        maxEvacuationDistance: 35,
        fireResistanceOfStructure: 90,
      },
      avac: {
        hasHVACProject: true,
        hasVentilationSystem: true,
        ventilationType: "mechanical_supply_extract",
        hasKitchenExtraction: true,
        hasBathroomExtraction: true,
        hasDuctwork: true,
        hasAirQualityControl: false,
        hasMaintenancePlan: true,
        hasFGasCompliance: true,
        hasRadonProtection: false,
      },
      electrical: {
        supplyType: "three_phase",
        contractedPower: 10.35,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 5,
        hasEquipotentialBonding: true,
        wiringType: "embedded",
        cableType: "h07v",
        hasCorrectCableSizing: true,
        numberOfCircuits: 8,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: true,
        hasEmergencyCircuit: true,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      telecommunications: {
        itedEdition: "4",
        hasATE: true,
        hasATI: true,
        numberOfATI: 1,
        hasCopperCabling: true,
        copperCableCategory: "6a",
        hasFiberOptic: true,
        fiberType: "single_mode",
        hasCoaxialCabling: true,
        hasFoorDistribution: true,
        hasRiserCableway: true,
        hasIndividualDucts: true,
        rj45OutletsPerDwelling: 6,
        coaxialOutletsPerDwelling: 3,
        fiberOutletsPerDwelling: 2,
        isUrbanization: false,
        hasITURProject: false,
        hasUndergroundDucts: false,
        hasCEE: true,
        hasITEDCertification: true,
        installerITEDLicense: true,
      },
      envelope: {
        externalWallUValue: 0.35,
        externalWallArea: 500,
        roofUValue: 0.30,
        roofArea: 250,
        floorUValue: 0.40,
        floorArea: 250,
        windowUValue: 2.40,
        windowArea: 80,
        windowSolarFactor: 0.35,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.30,
        airChangesPerHour: 0.6,
        hasHRV: true,
        hrvEfficiency: 70,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "heat_pump",
        dhwSystem: "heat_pump",
        hasSolarPV: true,
        solarPVCapacity: 30,
        hasSolarThermal: true,
        solarThermalArea: 50,
      },
      acoustic: {
        buildingLocation: "mixed",
        hasAirborneInsulation: true,
        airborneInsulationValue: 53,
        hasImpactInsulation: true,
        impactInsulationValue: 55,
        hasFacadeInsulation: true,
        facadeInsulationValue: 33,
        hasEquipmentNoiseControl: true,
        hasAcousticProject: true,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: true,
        doorWidths: 0.90,
        corridorWidths: 1.40,
        hasAccessibleWC: true,
        hasAccessibleParking: true,
      },
      elevators: {
        hasElevator: true,
        numberOfElevators: 2,
        elevatorType: "passenger",
        hasCEMarking: true,
        hasMaintenanceContract: true,
        hasPeriodicInspection: true,
        hasEmergencyCommunication: true,
        hasPitAndHeadroom: true,
        hasAccessibleElevator: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
      waste: {
        hasWasteManagementPlan: true,
        hasSortingOnSite: true,
        hasLicensedTransporter: true,
        hasLicensedDestination: true,
        hasWasteRegistration: true,
        hasDemolitionAudit: false,
        recyclingPercentageTarget: 70,
      },
    },
  ),

  // ── Reabilitação de Edifício ────────────────────────
  template(
    "reabilitacao",
    "templateReabilitacao",
    "templateReabilitacaoDesc",
    "🔨",
    "residential",
    {
      name: "Reabilitação de Edifício",
      buildingType: "residential",
      isRehabilitation: true,
      grossFloorArea: 300,
      usableFloorArea: 240,
      numberOfFloors: 3,
      buildingHeight: 10,
      numberOfDwellings: 4,
      yearBuilt: 1940,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: true,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: false,
        ceilingHeight: 3.20,
        hasNaturalLight: true,
        hasCrossVentilation: false,
      },
      structural: {
        structuralSystem: "masonry",
        seismicZone: "1.3",
        soilType: "C",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "shallow",
        hasSeismicDesign: true,
        ductilityClass: "DCL",
      },
      fireSafety: {
        utilizationType: "I",
        riskCategory: "2",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.0,
        numberOfExits: 1,
        maxEvacuationDistance: 20,
        fireResistanceOfStructure: 60,
      },
      envelope: {
        externalWallUValue: 0.60,
        externalWallArea: 180,
        roofUValue: 0.45,
        roofArea: 100,
        floorUValue: 0.60,
        floorArea: 100,
        windowUValue: 3.50,
        windowArea: 25,
        windowSolarFactor: 0.50,
        windowFrameType: "wood",
        linearThermalBridges: 0.60,
        airChangesPerHour: 0.8,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "gas_boiler",
        coolingSystem: "none",
        dhwSystem: "gas_boiler",
        hasSolarPV: false,
        hasSolarThermal: true,
        solarThermalArea: 4,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: true,
        isProtectedArea: false,
      },
    },
  ),

  // ── Moradia T4 ──────────────────────────────────────
  template(
    "moradia_t4",
    "templateMoradiaT4",
    "templateMoradiaT4Desc",
    "🏡",
    "residential",
    {
      name: "Moradia T4",
      buildingType: "residential",
      grossFloorArea: 280,
      usableFloorArea: 240,
      numberOfFloors: 3,
      buildingHeight: 10,
      numberOfDwellings: 1,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: false,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 2.80,
        hasNaturalLight: true,
        hasCrossVentilation: true,
      },
      structural: {
        structuralSystem: "reinforced_concrete",
        seismicZone: "1.3",
        soilType: "B",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "shallow",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "I",
        riskCategory: "1",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 0.9,
        numberOfExits: 2,
        maxEvacuationDistance: 15,
        fireResistanceOfStructure: 60,
      },
      avac: {
        hasHVACProject: false,
        hasVentilationSystem: false,
        ventilationType: "natural",
        hasKitchenExtraction: true,
        hasBathroomExtraction: true,
        hasDuctwork: false,
        hasAirQualityControl: false,
        hasMaintenancePlan: false,
        hasFGasCompliance: false,
        hasRadonProtection: false,
      },
      electrical: {
        supplyType: "single_phase",
        contractedPower: 13.8,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 10,
        hasEquipotentialBonding: true,
        wiringType: "embedded",
        cableType: "h07v",
        hasCorrectCableSizing: true,
        numberOfCircuits: 12,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: true,
        hasEmergencyCircuit: false,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      envelope: {
        externalWallUValue: 0.35,
        externalWallArea: 220,
        roofUValue: 0.30,
        roofArea: 100,
        floorUValue: 0.40,
        floorArea: 100,
        windowUValue: 2.40,
        windowArea: 40,
        windowSolarFactor: 0.30,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.30,
        airChangesPerHour: 0.6,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "heat_pump",
        dhwSystem: "heat_pump",
        hasSolarPV: true,
        solarPVCapacity: 5.0,
        hasSolarThermal: true,
        solarThermalArea: 6,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: false,
        doorWidths: 0.80,
        corridorWidths: 1.10,
        hasAccessibleWC: true,
        hasAccessibleParking: false,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
    },
  ),

  // ── Armazém Industrial ──────────────────────────────
  template(
    "armazem_industrial",
    "templateArmazemIndustrial",
    "templateArmazemIndustrialDesc",
    "🏭",
    "commercial",
    {
      name: "Armazém Industrial",
      buildingType: "industrial",
      grossFloorArea: 1500,
      usableFloorArea: 1450,
      numberOfFloors: 1,
      buildingHeight: 8,
      numberOfDwellings: 0,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: false,
        respectsCommonParts: false,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 6.0,
        hasNaturalLight: true,
        hasCrossVentilation: true,
      },
      structural: {
        structuralSystem: "steel",
        seismicZone: "1.3",
        soilType: "B",
        importanceClass: "II",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "shallow",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "XII",
        riskCategory: "2",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: true,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.2,
        numberOfExits: 3,
        maxEvacuationDistance: 40,
        fireResistanceOfStructure: 60,
      },
      avac: {
        hasHVACProject: false,
        hasVentilationSystem: false,
        ventilationType: "natural",
        hasKitchenExtraction: false,
        hasBathroomExtraction: true,
        hasDuctwork: false,
        hasAirQualityControl: false,
        hasMaintenancePlan: false,
        hasFGasCompliance: false,
        hasRadonProtection: false,
      },
      electrical: {
        supplyType: "three_phase",
        contractedPower: 100,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 300,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 10,
        hasEquipotentialBonding: true,
        wiringType: "cable_tray",
        cableType: "xv",
        hasCorrectCableSizing: true,
        numberOfCircuits: 20,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: false,
        hasEmergencyCircuit: true,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      envelope: {
        externalWallUValue: 0.50,
        externalWallArea: 400,
        roofUValue: 0.40,
        roofArea: 1500,
        floorUValue: 0.60,
        floorArea: 1500,
        windowUValue: 3.50,
        windowArea: 30,
        windowSolarFactor: 0.40,
        windowFrameType: "aluminum_no_break",
        linearThermalBridges: 0.50,
        airChangesPerHour: 1.2,
        hasHRV: false,
      },
      systems: {
        heatingSystem: "none",
        coolingSystem: "none",
        dhwSystem: "electric",
        hasSolarPV: true,
        solarPVCapacity: 20,
        hasSolarThermal: false,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: false,
        doorWidths: 1.20,
        corridorWidths: 2.00,
        hasAccessibleWC: true,
        hasAccessibleParking: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
    },
  ),

  // ── Edifício Público (Escola/Clínica) ───────────────
  template(
    "edificio_publico",
    "templateEdificioPublico",
    "templateEdificioPublicoDesc",
    "🏫",
    "commercial",
    {
      name: "Edifício Público",
      buildingType: "commercial",
      grossFloorArea: 800,
      usableFloorArea: 720,
      numberOfFloors: 2,
      buildingHeight: 8,
      numberOfDwellings: 0,
      architecture: {
        hasCivilCodeCompliance: true,
        hasRainwaterDrainage: true,
        isHorizontalProperty: false,
        respectsCommonParts: true,
        hasBuildingPermitDesign: true,
        meetsRGEU: true,
        ceilingHeight: 3.20,
        hasNaturalLight: true,
        hasCrossVentilation: true,
      },
      structural: {
        structuralSystem: "reinforced_concrete",
        seismicZone: "1.3",
        soilType: "B",
        importanceClass: "III",
        hasStructuralProject: true,
        hasGeotechnicalStudy: true,
        foundationType: "shallow",
        hasSeismicDesign: true,
        ductilityClass: "DCM",
      },
      fireSafety: {
        utilizationType: "IV",
        riskCategory: "2",
        hasFireDetection: true,
        hasFireAlarm: true,
        hasSprinklers: false,
        hasEmergencyLighting: true,
        hasFireExtinguishers: true,
        evacuationRouteWidth: 1.5,
        numberOfExits: 4,
        maxEvacuationDistance: 30,
        fireResistanceOfStructure: 60,
      },
      avac: {
        hasHVACProject: true,
        hasVentilationSystem: true,
        ventilationType: "mechanical_supply_extract",
        hasKitchenExtraction: true,
        hasBathroomExtraction: true,
        hasDuctwork: true,
        hasAirQualityControl: true,
        hasMaintenancePlan: true,
        hasFGasCompliance: true,
        hasRadonProtection: false,
      },
      electrical: {
        supplyType: "three_phase",
        contractedPower: 60,
        hasProjectApproval: true,
        hasMainCircuitBreaker: true,
        hasResidualCurrentDevice: true,
        rcdSensitivity: 30,
        hasIndividualCircuitProtection: true,
        hasSurgeProtection: true,
        hasEarthingSystem: true,
        earthingResistance: 10,
        hasEquipotentialBonding: true,
        wiringType: "embedded",
        cableType: "xv",
        hasCorrectCableSizing: true,
        numberOfCircuits: 18,
        hasSeparateLightingCircuits: true,
        hasSeparateSocketCircuits: true,
        hasDedicatedApplianceCircuits: true,
        hasBathroomZoneCompliance: true,
        hasOutdoorIPProtection: true,
        hasEVCharging: false,
        hasEmergencyCircuit: true,
        hasDistributionBoardLabelling: true,
        hasSchematicDiagram: true,
      },
      envelope: {
        externalWallUValue: 0.35,
        externalWallArea: 300,
        roofUValue: 0.30,
        roofArea: 400,
        floorUValue: 0.40,
        floorArea: 400,
        windowUValue: 2.40,
        windowArea: 80,
        windowSolarFactor: 0.30,
        windowFrameType: "aluminum_thermal_break",
        linearThermalBridges: 0.30,
        airChangesPerHour: 0.6,
        hasHRV: true,
      },
      systems: {
        heatingSystem: "heat_pump",
        coolingSystem: "central_ac",
        dhwSystem: "heat_pump",
        hasSolarPV: true,
        solarPVCapacity: 15,
        hasSolarThermal: true,
        solarThermalArea: 8,
        lightingPowerDensity: 8,
      },
      accessibility: {
        hasAccessibleEntrance: true,
        hasElevator: true,
        doorWidths: 0.90,
        corridorWidths: 1.50,
        hasAccessibleWC: true,
        hasAccessibleParking: true,
      },
      licensing: {
        projectPhase: "licensing",
        hasArchitecturalProject: true,
        hasSpecialtyProjects: true,
        hasTermoDeResponsabilidade: true,
        hasMunicipalApproval: false,
        hasConstructionLicense: false,
        hasUtilizationLicense: false,
        hasTechnicalDirector: true,
        isInARU: false,
        isProtectedArea: false,
      },
    },
  ),
];

export function getTemplate(id: string): ProjectTemplate | undefined {
  return PROJECT_TEMPLATES.find(t => t.id === id);
}
